# coding: utf-8

"""
    Sibyl Core API

    Core API for Sibyl Numerology Bot

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sibyl_core_sdk.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_users_id_delete(self) -> None:
        """Test case for users_id_delete

        Delete user by UUID
        """
        pass

    def test_users_id_get(self) -> None:
        """Test case for users_id_get

        Get user by UUID
        """
        pass

    def test_users_id_put(self) -> None:
        """Test case for users_id_put

        Update user by UUID
        """
        pass

    def test_users_post(self) -> None:
        """Test case for users_post

        Create a new user
        """
        pass

    def test_users_telegram_telegram_id_get(self) -> None:
        """Test case for users_telegram_telegram_id_get

        Get user by Telegram ID
        """
        pass

    def test_users_telegram_telegram_id_put(self) -> None:
        """Test case for users_telegram_telegram_id_put

        Update user by Telegram ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
