# coding: utf-8

"""
    Sibyl Core API

    Core API for Sibyl Numerology Bot  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from sibyl_core_sdk.paths.users_id.delete import UsersIdDelete
from sibyl_core_sdk.paths.users_id.get import UsersIdGet
from sibyl_core_sdk.paths.users_id.put import UsersIdPut
from sibyl_core_sdk.paths.users.post import UsersPost
from sibyl_core_sdk.paths.users_telegram_telegram_id.get import UsersTelegramTelegramIdGet
from sibyl_core_sdk.paths.users_telegram_telegram_id.put import UsersTelegramTelegramIdPut


class DefaultApi(
    UsersIdDelete,
    UsersIdGet,
    UsersIdPut,
    UsersPost,
    UsersTelegramTelegramIdGet,
    UsersTelegramTelegramIdPut,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
