# coding: utf-8

"""
    Sibyl Core API

    Core API for Sibyl Numerology Bot  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import sibyl_core_sdk
from sibyl_core_sdk.model.user import User
from sibyl_core_sdk import configuration


class TestUser(unittest.TestCase):
    """User unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
