# coding: utf-8

# flake8: noqa

"""
    Sibyl Core API

    Core API for Sibyl Numerology Bot  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from sibyl_core_sdk.api_client import ApiClient

# import Configuration
from sibyl_core_sdk.configuration import Configuration

# import exceptions
from sibyl_core_sdk.exceptions import OpenApiException
from sibyl_core_sdk.exceptions import ApiAttributeError
from sibyl_core_sdk.exceptions import ApiTypeError
from sibyl_core_sdk.exceptions import ApiValueError
from sibyl_core_sdk.exceptions import ApiKeyError
from sibyl_core_sdk.exceptions import ApiException
